### ISSUE TITLE
how to merge layers into PSPNet?

### ISSUE THREAD

**Issue by EchoAmor** [hszhao/PSANet#10]
Hi ! I have merged layers you said into PSPNet ,but when I make it appears following errors,can you tell me how to fix this?? 

I also want to know whether I can train this model because you didn't mention it in this repository.
Thanks very much! 

Here are some errors:

`src/caffe/layers/pointwise_spatial_attention_layer.cpp: In member function ‘virtual void caffe::PointwiseSpatialAttentionLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
src/caffe/layers/pointwise_spatial_attention_layer.cpp:12:3: error: ‘PointwiseSpatialAttentionParameter’ was not declared in this scope
src/caffe/layers/pointwise_spatial_attention_layer.cpp:71:3: error: ‘PointwiseSpatialAttentionParameter_PSAType_COLLECT’ was not declared in this scope
src/caffe/layers/pointwise_spatial_attention_layer.cpp:71:3: error: ‘PointwiseSpatialAttentionParameter_PSAType_DISTRIBUTE’ was not declared in this scope
src/caffe/layers/pointwise_spatial_attention_layer.cpp: In function ‘void caffe::PSAForward_buffer_mask_collect_cpu(int, int, int, int, int, int, int, const Dtype*, Dtype*)’:
src/caffe/layers/pointwise_spatial_attention_layer.cpp:116:51: error: there are no arguments to ‘max’ that depend on a template parameter, so a declaration of ‘max’ must be available [-fpermissive]
src/caffe/layers/pointwise_spatial_attention_layer.cu(201): error: class "caffe::LayerParameter" has no member "pointwise_spatial_attention_param"
          detected during instantiation of "void caffe::PointwiseSpatialAttentionLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(220): here
8 errors detected in the compilation of "/tmp/tmpxft_00004960_00000000-19_pointwise_spatial_attention_layer.compute_52.cpp1.ii".
make: *** [.build_release/cuda/src/caffe/layers/pointwise_spatial_attention_layer.o] Error 1
`

**Comment by frozenbeanxxx** [comment]
you also need to merge PSANet/evaluation to PSPNet
