### ISSUE TITLE
HoleConvolution

### ISSUE THREAD

**Issue by 994374821** [hszhao/PSANet#3]
I have some confusion about your 'HoleConvolution' layer when I try to evaluate your pretrained model. I did not find the definition of 'HoleConvolution' which appears in 'prototxt' file. Where the 'HoleConvolution' layer define? Thanks.

**Comment by EthanZhangYi** [comment]
Codes have been updated.
See commit 8735a59d7ade55517ef22562663121bd3cb88db7
