### ISSUE TITLE
evaluate error

### ISSUE THREAD

**Issue by 994374821** [hszhao/PSANet#4]
When I evaluate psanet50_voc2012_465.prototxt net use your pretained psanet50_voc2012_d5fc37.caffemodel, there is some errors.
`F0920 09:00:23.963999  5519 net.cpp:829] Cannot copy param 0 weights from layer 'PSA_COLLECT_fc2'; shape mismatch.  Source param shape is 13689 512 1 1 (7008768); target param shape is 3481 512 1 1 (1782272). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer`
But the ‘PSA_COLLECT_fc2’ layer's output channel is 3481in your psanet50_voc2012_465.prototxt.
layer {
  name: "PSA_COLLECT_fc2"
  type: "Convolution"
  bottom: "PSA_COLLECT_fc1"
  top: "PSA_COLLECT_fc2"
  param {
    lr_mult: 10
    decay_mult: 1
  }
  convolution_param {
    num_output:  3481 # 59*59
    kernel_size: 1
    stride: 1
    weight_filler {
      type: "msra"
    }
    bias_term: false
  }
}

**Comment by hszhao** [comment]
The prototxt files have been updated.
